package com.guarda.ethereum.models.constants;

/**
 *
 * Created by SV on 18.08.2017.
 */

public interface Guarda {

    String GUARDA_ETC_URL = "https://etc.guarda.co";
    String GUARDA_ETH_URL = "https://eth.guarda.co";
    String GUARDA_LOGGING = "https://guarda.co";
    String GUARDA_INRETNAL = "/api/v2/internal/";

    //Logger error types
    String ERROR_SENDING_WRONG_NETWORK = "SHIELDED_SENDING_WNE";
    String ERROR_SENDING_COMMON_ZCASHEXCEPTION = "SHIELDED_SENDING_COMMON_ZCASHEXCEPTION";
    String ERROR_SENDING_COMMON_EXCEPTION = "SHIELDED_SENDING_COMMON_EXCEPTION";
    String ERROR_SENDING_Z_ADDRESS_SYNCING = "SHIELDED_SENDING_Z_ADDRESS_SYNCING";
    String ERROR_SENDING_BUILDING_Z_Z = "SHIELDED_SENDING_BUILDING_Z_Z";
    String ERROR_SENDING_BUILDING_Z_T = "SHIELDED_SENDING_BUILDING_Z_T";
    String ERROR_SENDING_BUILDING_T_Z = "SHIELDED_SENDING_BUILDING_T_Z";
    String ERROR_SENDING_BUILDING_T_T = "SHIELDED_SENDING_BUILDING_T_T";
    String ERROR_SENDING_NODE_RESPONSE = "SHIELDED_SENDING_NODE_RESPONSE";
    //Logger success type
    String SENDING_SUCCESS = "SHIELDED_SENDING_SUCCESS";

}
