package com.guarda.ethereum.models.constants;

public interface RequestCode {

    int CONFIRM_PIN_CODE_FOR_CREATE_WALLET = 101;
    int CONFIRM_PIN_CODE_FOR_BACKUP_WALLET = 102;
    int QR_CODE_REQUEST_CODE = 50;
    int RESTORE_FROM_STOP_PIN_CODE_REQUEST = 55;
    int RESTORE_FROM_STOP_PIN_CODE_REQUEST_SIMPLE_TRACK = 56;
    int CONFIRM_PIN_CODE_REQUEST = 60;
    int CONFIRM_PIN_CODE_REQUEST_MA = 61;
    int SELECT_JSON_FILE = 62;
}
